### ISSUE TITLE
Location of Services (3)

### ISSUE THREAD

**Issue by AqilSidek** [techie-girl/dalmap#12]
As a student, I want to know the location of services (i.e. Registrar's Office) so that I can navigate between them

8 hours

**Comment by JScanl** [comment]
List of services in our 3 locations
Killam:
https://libraries.dal.ca/hours-locations/killam.html
Help Desk
Circulation Desk
Archives
Collections
Subway
Second Cup
Bistro
Bathrooms

Henry Hicks:
Registrars Office
Student Accounts
Finaical Services
Presidents Office?

Goldberg:
Second Cup
Help Desk
Learning Center
Shift key labs

**Comment by techie-girl** [comment]
Killam Memorial Library:
https://libraries.dal.ca/hours-locations/killam.html
Help Desk- South Common 
Circulation Desk- Lobby 
Archives & Special Collections Reading Room - 5th Floor
Collections - Lobby 
Subway - North of Atrium
Second Cup - South of Atrium 
Bistro - East of Atrium

Henry Hicks:
Registrars Office- First floor, Room 130
Student Accounts 7 Financial Services- Basement, Room 29
Dalhousie University Faculty of Graduate Studies- Third floor, Room 314
Presidents Office - First floor, Room 108

Goldberg:
Second Cup- Atrium
Help Desk - First Floor 
Learning Centre - Send Floor, Room Room 426
Shift key labs - Forth Floor, Room 426
